### PR TITLE
Add brunette for codestyle correction and linting

### PR DESCRIPTION
**Pull request by mmulich**
This adds codestyle linting and automated correct for python code.

### CODE REVIEW

**Comment by bluemellophone** [comment]
The `setup.cfg` file has a missiing configuration block for Flake8, as compared to the original branch here: https://github.com/WildbookOrg/wbia-vtool/blob/automated-wheel-w-macports/setup.cfg

**Comment by mmulich** [comment]
I had removed flake8 from the change. I'll add it in and redo the blackening commit.

I removed flake8 from pre-commit, because brunette is basically doing that anyhow, no sense in running it twice, right?

**Comment by bluemellophone** [comment]
It is stil required because Brunette won't check all of the same things as Flake8.

For example, Brunette will not remove references to unused packages that are imported, where Flake8 will throw an error.

**Comment by mmulich** [comment]
Ok, I'll add flake8 to this PR then.

**Comment by mmulich** [comment]
I've added flake8, but it has several errors. That will likely need to be picked through. I don't feel comfortable doing that now without a reliable set of tests running. So I'll punt that to a future PR.

**Pull request merged**
